#include "Onewire.h"
#include "onewire_library.pio.h"        // generated by pioasm

bool Onewire::init (PIO pio, uint offset, uint gpio)
{
    return ow_init(&ow, pio, (uint)offset, (uint)gpio);
}

void Onewire::send (uint data)
{
    ow_send(&ow, data);
}

uint8_t Onewire::read ()
{
    return ow_read(&ow);
}

bool Onewire::reset ()
{
    return ow_reset(&ow);
}

int32_t Onewire::romsearch (uint64_t *romcodes, int maxdevs, uint command)
{
    return ow_romsearch (&ow, romcodes, maxdevs, command);
}