#include <stdint.h>


extern "C" {
    // The onewire_library is not set up to be compiled via C++
    // This is a pretty hardcore workaround, but it works:
    #include "onewire_library.h"
}

#include "hardware/pio.h"
//#include "hardware/clocks.h"            // for clock_get_hz() in generated header
//#include "onewire_library.pio.h"        // generated by pioasm

class Onewire {
    public:
        bool init (PIO pio, uint offset, uint gpio);
        void send (uint data);
        uint8_t read ();
        bool reset ();
        int32_t romsearch (uint64_t *romcodes, int maxdevs, uint command);

    private:
        OW ow;
};